version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - './files/config:/etc/gitlab'
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab

volumes:
  logs:
    external: false
  data:
    external: false