version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    # настроить монтирование разделов для конфигурации nginx
    # volumes:
    #   - ./:/var/www
    #   - ./nginx/conf.d/:/etc/nginx/conf.d/