version: '3'

services:
  youtrack:
    container_name: youtrack
    image: jetbrains/youtrack:2020.6.3319
    ports:
      - 80:8080
    volumes:
      - data:/opt/youtrack/data
      - conf:/opt/youtrack/conf
      - logs:/opt/youtrack/logs
      - backups:/opt/youtrack/backups

volumes:
  data:
    external: false
  conf:
    external: false
  logs:
    external: false
  backups:
    external: false